# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

config:
  target: "http://ekko-ekkos-1XLES732DWZDL-738214756.us-east-2.elb.amazonaws.com/loadtest"
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiYXBwTmFtZSI6ImxvYWR0ZXN0IiwiaWF0IjoxNjIxNjM3NTE4fQ.ekb_asb5BXhMOlCcFM0yyRC2qAcvBn3K-0yMHsjHIvc"
      uuid: "hi"
  phases:
    - duration: 300
      arrivalRate: 1
    - duration: 300
      arrivalRate: 2

scenarios:
  - name: A chatty user
    engine: socketio-v3
    flow:
      - emit: ["subscribe", { channels: ["greeting"], uuid: "nobody" }]
      - think: 5
      - loop:
          - emit:
              [
                "publish",
                { channel: "greeting", message: { text: "my message" } },
              ]
          - think: 5
        count: 10
      - think: 300
