# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

config:
  target: "http://ekko-ekkos-YK9SB7GQBXVU-1280264013.us-east-2.elb.amazonaws.com/loadtest"
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiYXBwTmFtZSI6ImxvYWR0ZXN0IiwiaWF0IjoxNjIxNTU2MTM2fQ.TFcvBGww4qgg04snU59En9pJEESD2otToqkdASn-FZg"
      uuid: "hi"
  phases:
    - duration: 10
      arrivalRate: 1
    - duration: 10
      arrivalRate: 5
  variables:
    greeting:
      ["hello", "goedemorgen", "добрый день", "guten tag", "bonjour", "hola"]
  processor: "./functions.js"

scenarios:
  - name: "A user that just lurks"
    weight: 75
    engine: socketio-v3
    flow:
      - get:
          url: "/"
      - emit:
        [
          "subscribe", {channels: ["greeting"], uuid: "lurker-{{ $randomString() }}"}
        ]
      - think: 60

  - name: "A mostly quiet user"
    weight: 15
    engine: socketio-v3
    flow:
      - get:
          url: "/"
      - emit:
        [
          "subscribe", {channels: ["greeting"], uuid: "quiet-{{ $randomString() }}"}
        ]
      - think: 5
      - emit:
        [
          "publish", {channel: "greeting", message: {text: "{{ greeting }}"}}
        ]
      - think: 60

  - name: "A chatty user"
    weight: 10
    engine: socketio-v3
    flow:
      - get:
          url: "/"
      - emit:
          [
          "subscribe", {channels: ["greeting"], uuid: "chatty-{{ $randomString() }}"}
          ]
      - think: 5
      - emit:
          [
            "publish", {channel: "greeting", message: {text: "{{ greeting }}"}, uuid: "chatty-{{ $randomString() }}"}
          ]
      - loop:
          - function: "setMessage"
          - emit:
              [
                "publish", {channel: "greeting", message: {text: "{{ message }}"}}
              ]
          - think: 10
        count: 10
      - think: 60
