config:
  target: "http://ekko-ekkos-1QZ0F5RQERLFR-1436539638.us-east-1.elb.amazonaws.com/loadtest"
  phases:
    - duration: 1
      arrivalRate: 1
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImFwcE5hbWUiOiJsb2FkdGVzdCIsImlhdCI6MTYyMTYzNDIwNX0.B-Uv1ETUw3xvYF74PPrvfUTFcHoktfpHerGefniOaqQ"
      uuid: "hi"
scenarios:
  - name: An IoT Device
    engine: socketio-v3
    flow:
      # - emit: ["subscribe", { channels: ["greeting"], uuid: "nobody" }]
      - think: 120
      - loop:
          - emit:
              [
                "publish",
                { channel: "greeting", message: { text: "my message" } },
              ]
          - think: 1
        count: 250
      - think: 1
