config:
  target: "http://ekko-ekkos-144LA4X918SBV-105734816.us-east-2.elb.amazonaws.com/load-testing"
  phases:
    - duration: 120
      arrivalRate: 10
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiYXBwTmFtZSI6ImxvYWQtdGVzdGluZyIsImlhdCI6MTYyMDE2NDA2OH0.Is-0BLboOa0nPIPATPL0YpnrL1RbbAehaDDUoe6s24M"
      uuid: "load-tester"
scenarios:
  - name: ekko Test
    engine: socketio-v3
    flow:
      - think: 120
