config:
  target: "http://ekko-ekkos-1JWA751RZNMEI-1720933133.us-west-1.elb.amazonaws.com"
  phases:
    - duration: 200
      arrivalRate: 25
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImFwcE5hbWUiOiJsb2FkLXRlc3RpbmciLCJpYXQiOjE2MjAxODU4Mzh9.efk6CoAJbbqQtYbX_BvZ0txHagIaNFjvyHPhbGhHZi4"
scenarios:
  - name: ekko Test
    engine: socketio-v3
    flow:
      - think: 200
