config:
  target: "http://ekko-ekkos-1XLES732DWZDL-738214756.us-east-2.elb.amazonaws.com/loadtest"
  phases:
    - duration: 1
      arrivalRate: 1
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiYXBwTmFtZSI6ImxvYWR0ZXN0IiwiaWF0IjoxNjIxNjM3NTE4fQ.ekb_asb5BXhMOlCcFM0yyRC2qAcvBn3K-0yMHsjHIvc"
      uuid: "hi"
scenarios:
  - name: A publisher
    engine: socketio-v3
    flow:
      # - emit: ["subscribe", { channels: ["greeting"], uuid: "nobody" }]
      - think: 400
      - loop:
          - emit:
              [
                "publish",
                { channel: "greeting", message: { text: "my message" } },
              ]
          - think: 1
        count: 100
      - think: 1
