config:
  target: "http://ekko-ekkos-YK9SB7GQBXVU-1280264013.us-east-2.elb.amazonaws.com/loadtest"
  phases:
    - duration: 10
      arrivalRate: 1
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiYXBwTmFtZSI6ImxvYWR0ZXN0IiwiaWF0IjoxNjIxNTU2MTM2fQ.TFcvBGww4qgg04snU59En9pJEESD2otToqkdASn-FZg"
      uuid: "hi"
scenarios:
  - name: ekko Test
    engine: socketio-v3
    flow:
      - emit:
          [
            "publish",
            { channel: "greeting", message: { text: "hi" }, uuid: "none" },
          ]
      - think: 10
