config:
  target: "http://ekko-ekkos-DXOLAZG8XB-14233476.us-east-2.elb.amazonaws.com/load-testing"
  phases:
    - duration: 10
      arrivalRate: 1
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiYXBwTmFtZSI6ImxvYWQtdGVzdGluZyIsImlhdCI6MTYyMDE1MDcyNH0.c7Y-3OQfhH6HMKqx7MPQ_-_3BXdsVeGktWb5BSY2xjo"
      uuid: "load-tester"
scenarios:
  - name: ekko Test
    engine: socketio-v3
    flow:
      - emit:
          [
            "publish",
            { channel: "load-test", message: { text: "hi" }, uuid: "none" },
          ]
      - think: 3
