config:
  target: "http://ekko-ekkos-1JWA751RZNMEI-1720933133.us-west-1.elb.amazonaws.com"
  phases:
    - duration: 60000
      arrivalRate: 3
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6dHJ1ZSwiYXBwTmFtZSI6ImxvYWQtdGVzdGluZyIsImlhdCI6MTYyMDE4NDcwOX0.T2MaOl0BOa34HSWCOKRdG3OSAvRDIPgGIzZieItBSlQ"
      uuid: "load-tester"
scenarios:
  - name: ekko Test
    engine: socketio-v3
    flow:
      - think: 60000
