# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

config:
  target: "http://ekko-ekkos-1QZ0F5RQERLFR-1436539638.us-east-1.elb.amazonaws.com/loadtest"
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImFwcE5hbWUiOiJsb2FkdGVzdCIsImlhdCI6MTYyMTYzNDIwNX0.B-Uv1ETUw3xvYF74PPrvfUTFcHoktfpHerGefniOaqQ"
      uuid: "hi"
  phases:
    - duration: 1000
      arrivalRate: 20

scenarios:
  - name: An IoT Device
    engine: socketio-v3
    flow:
      # - emit: ["subscribe", { channels: ["greeting"], uuid: "nobody" }]
      - think: 1000
      # - loop:
      #     - emit:
      #         [
      #           "publish",
      #           { channel: "greeting", message: { text: "my message" } },
      #         ]
      #     - think: 60
      #   count: 10
      # - think: 1
