config:
  target: "http://ekko-ekkos-1QZ0F5RQERLFR-1436539638.us-east-1.elb.amazonaws.com/lt"
  phases:
    - duration: 10
      arrivalRate: 1
  engines:
    socketio-v3: {}
  socketio:
    transports: ["websocket"]
    auth:
      jwt: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbiI6ZmFsc2UsImFwcE5hbWUiOiJsdCIsImlhdCI6MTYyMTYwMzEyOH0.mPxoZJ1hMoa2Voa5W1xyZPxczUPwiVujRfRMwkLcJGs"
      uuid: "hi"
scenarios:
  - name: ekko Test
    engine: socketio-v3
    flow:
      - emit:
          [
            "publish",
            { channel: "greeting", message: { text: "hi" }, uuid: "none" },
          ]
      - think: 10
